<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2018
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

// API
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG']['API']['helpers'][0] = 'API Helfer';
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG']['API']['helpers'][1] = 'API Helfer sind eine Sammlung von hilfreichen Funktionen für die CustomCatalog API';
