<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['mode_api_helpers'] 			= $GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['mode'];
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['mode_api_helpers']['xml']		= 'XML Daten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action']['helpers']			= 'API Helfer';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action']['xml']				= 'Wert aus XML [xpath]';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['valueSRC_xpath'][1]			= 'Geben Sie den regulären xpath Ausdruck ein.'; 
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['valueSRC_xpath'][0]			= 'Wertermittlung via xpath';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['valueSRC_xpath'][1]			= 'Geben Sie den regulären xpath Ausdruck ein. <a href="http://php.net/manual/de/simplexmlelement.xpath.php" target="_blank">Dokumentation</a>. <br>Attribute in xml-Nodes können über Objekt-Pfeilschreibweise abgefragt werden z.B. node/subnode->attribute'; 