<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2018
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['source']['xml']				= 'XML-Datei';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['target']['xml']				= 'XML-Datei';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['uniqueSource']['xml_info'] 	= 'XML-Dateien unterliegen keiner allgemein-gültige Struktur. Eine Ermittlung von Schlüsselfeldern kann nur individuell erfolgen. Nutzen Sie dafür den options_callback des Feldes "tl_pct_customcatalog_api.uniqueSource". <a style="text-decoration:underline" href="https://docs.contao.org/books/api/dca/callbacks.html" target="_blank">Contao-Handbuch</a>';